name: Upload Dummy Data to S3
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Runs every 20 minutes
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Dummy Files (10MB each)
        run: |
          for i in {1..10}; do
            TIMESTAMP=$(date +%s%N)  # Get current timestamp in nanoseconds for unique file names
            dd if=/dev/zero of=file_${TIMESTAMP}_$i.txt bs=1M count=10; 
          done

      - name: Upload to First S3 Bucket
        run: aws s3 cp ./ s3://cloud-storage-bucket54/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Upload to Second S3 Bucket
        run: aws s3 cp ./ s3://testing554/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


