name: Upload Dummy Data to S3
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Dummy Files
        run: for i in {1..10}; do echo "test data" > file_$i.txt; done
      - name: Upload to S3
        run: aws s3 cp ./ s3://cloud-storage-bucket54/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
